travis:
  secure:
    BINSTAR_TOKEN: emTY+IyF5AA6GsAzNeJ775UzKLdZx0AaZymJr7bptCJrkU3Tet2I9A06nV+HQXWnP6+pTuZc8CxKtuqsx2Z5wQFL+WJkOSiEekYH76K/0cp2oJqWpNqZk5RG0Rn5MB2yrWlZgH1mQB5PlkNnJMh9G1WfUNaf0zTA3E+CeVBJV7nc9tTomrfDwor717BEEd8GPfKFA1GXCMOb2kdggUAuW55S8MbLoQT6zw+5zLeiXpa59djN5zlyQhWS/fZBPwjaI7z3RiaMrs9S2GsgQAwV9el5/Gh0TtTx32P9jpic9AMhjaKH4KY57HTx3neum9qu/4ehRIWbSJcs2v07PZq5m1QaePNzoPKdQpusqWfCWYqdK30SUo5zf7Xge7QWw6M7kvnJn9ibpDz7JGZ2ztYeLmUtjY1Ddz6TokeOmqZf4jsemAIahO/D5O1drnZDih1jDhNAZyvh+m6pLPFdRrRreEdRFlJhYy50W+mTXZsi6otnC782dtWkKoPniERef7nFiWe9O/1nxDSwsz+kTFexvbeWAiUNgMJZR2ybkND3idGg7d8mMWAqUjZOJncduqKcciREZg/ZWxOJLCcJ44O2bVusuYDNMH1c9pLdLRnMDOUqM6pkiT/f2JUbFfpgaEccvvLmD1TBh8Buv8w9UtQMka4x2gduEVFiG+KI8MrqEgw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
