travis:
  secure:
    BINSTAR_TOKEN: Ftu1FnSDZEIFyQ1nJIK0FRpzwjer1ZWO3ek2QLpG7eTOul2MDLVE8z1cGM2SnpkDYPAY/l7TvhsB/IiMkYePrD315LZFwx2g2L+mZS6JmqLI2apSpb/e7ja9lc0zlx+OyCBSvfgdo3NbbQnDQm6MLpceN7UiQw5TRsxaNCvjExq8g6jy2yuVQiuhHs1flBG2KM5i3KGoud3eoFzH97VXjQeOt9EQv6nquO3yL1ojxkStABcP6d3cPbvf7eie09u4Le1O4xWW5/SwMBeuRF4DXLf1bBUtRiiDsyRuZ5W5DAETuMif7Npy7xcjDfXQKYIEZEaM/vYCyux2kdWyByPJSKwDic9gqF6DrY6lPcQJosTjsUqtHeyQM+z6G/3R1lRViuhAGVtKTzvZ3GoK69sktAf9z8xCKy4sLXZMuttyCHKsWMHWbneLcJpvNFKKVO3QZauv8rzpSY3I8i3bg/bPanxvaJOMkxzxk8azJ4JiNb23Dk9udA3iM05Ks5b7KOfWY/Y926lW8wOQEh1LU71APTEyGyJuNORMnQ7R32AUvkh6Xnbp2QGOb4GX9vV3zc2N0QMeb4RIfCj1DdZTI3wLs6CjkfrmTvrXgQj5jb3bHZfaPXTFntXO2eNlTwlGxPbvCLX/79qcRjT3TEQ03dpvYxblgJ+OBpN9F0FtMnXUOSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
